### ISSUE TITLE
New Module: Raid Protection/Firewall

### ISSUE THREAD

**Issue by Seklfreak** [Seklfreak/Robyul2#16]
Self defined rules:
- one or multiple triggers:
  - join
  - message contains text, discord invite, link, embeds, attachments
  - number of mentions
  - mentions @ everyone, @ here
  - pressure
  - length of message
  - pool size
  - repeated message
- one or multiple triggers (with order):
  - mute
  - kick
  - ban
  - delete message
  - increase pressure
  - send notifications (Discord Channel, Discord DM, Maybe Pushover/SMS/similar API)
  - put member/message in pool with decay

(pressure similar to https://github.com/blackhole12/sweetiebot )

Offer pre defined rule sets.

**Comment by sn0w** [comment]
If this module becomes as good as it sounds I'll most likely ~~steal~~ merge it into the upstream 😮  

Would be awesome if you keep this issue updated with planned features or ideas 👍 
Raid protection is one of Karen's most requested features so far.

**Comment by Seklfreak** [comment]
@sn0w Awesome! I'm not sure when I will implement it but I will tell you when it's done. :)

Raid protection has a lot of potential for more sophisticated raid detection, and it's getting more important as raids are getting more common and bigger on discord. I hope I will be able to implement something useful. :D
