### ISSUE TITLE
.vscode: can't get gosfmt anymore

### ISSUE THREAD

**Issue by chanyoung** [Seklfreak/Robyul2#26]
Hi Sebastian.

There is no gosfmt tool anymore in Shixzie's repository. (or private?)

```
  1 // Place your settings in this file to overwrite default and user settings.
  2 {
  3     // go get github.com/Shixzie/gosfmt     <- it doesn't work
  4     // to use spaces instead of tabs
  5     "go.formatTool": "gosfmt",
  6     "go.formatFlags": [
  7         "-w",
  8         "-b",
  9         "-s"
 10     ],
 11     "editor.detectIndentation": false,
 12     "editor.tabSize": 4,
 13     "editor.insertSpaces": true,
 14     "files.autoSave": "afterDelay"
 15 }
```

Do you have any plans for using gofmt or other formatting tools instead of gosfmt?
* Change to gofmt means replacing spaces to tabs because gofmt only allows tab from 3 years ago.
I **fully respect** the coding style of Robyul2 project.

Thanks.
CPark

**Comment by Seklfreak** [comment]
Switching to go standard tools should be the best decision.

I removed .vscode, updated .editorconfig and ran gofmt over the whole project.

Thanks!
