### ISSUE TITLE
travis: check gofmt except vendor/...

### ISSUE THREAD

**Issue by chanyoung** [Seklfreak/Robyul2#28]
gofmt script in travis.yaml keeps failed due to the vendor/... files.

I think we don't really have to care about third-party repository's format.
How about change travis script to do not check third-party repos?

Here is my messy, silly sample script of this issue.

```
unset dirs files 
dirs=$(go list -f {{.Dir}} ./... | grep -v /vendor/)
for d in $dirs
do
    for f in $d/*.go
    do
        files="${files} $f"
    done
done
diff <(gofmt -d $files) <(echo -n)
```

gofmt checks all go type files recursively from given directories.
That means if gived a root project directory to gofmt, (in this case /.../Seklfreak/Robyul2) then gofmt will try to check under Robyul2/vendor/... directories too.
So I change to give a file list, not directory list.

It works well in my local PC (with bash).
![2017-08-19 15-41-12](https://user-images.githubusercontent.com/6683987/29484215-fe97d32e-84f4-11e7-8c98-270828edd05d.png)

Thanks.

**Comment by chanyoung** [comment]
assets.go is auto generated file by go-bindata and don't follow the rule by gofmt.
We need to exclude assets.go too.

**Comment by Seklfreak** [comment]
Very nice!

How about we use this to exclude both vendor and assets.go:
```
unset dirs files
dirs=$(go list -f {{.Dir}} ./... | grep -v /vendor/)
for d in $dirs
do
    for f in $d/*.go
    do
        if ! [[ $f =~ ^.+\/helpers\/assets\.go$ ]]; then
            files="${files} $f"
        fi
    done
done
diff <(gofmt -d $files) <(echo -n)
```

It's not pretty but it should do it's job.

**Comment by chanyoung** [comment]
Nice work!

That script can do it's job well!

**Comment by chanyoung** [comment]
Could you apply this script to travis.yaml ?
My fork repository isn't working with travis.

**Comment by Seklfreak** [comment]
done in 7137d7917b83b22d3049a4c43d6d98b40a140e70 and c1012703604032887b1c63b96ec2f613df05549f!
