### ISSUE TITLE
travis: go test exclude vendor directory

### ISSUE THREAD

**Issue by chanyoung** [Seklfreak/Robyul2#29]
Hi, similar travis issue.

Currently 'go test' doesn't support excluding vendor directory.
However it has discussed actively and seems like to be patched soon. (May be next golang version?)
How about to remove 'go test' until golang gives us to standard solution?

And the most important thing is, we don't have proper test code files yet.. :)

**Comment by Seklfreak** [comment]
Yeah, it's not doing anything yet anyway. If we implement tests we can use a similar approach to #28 (if it hasn't been patched yet). We can comment it out for now.

**Comment by Seklfreak** [comment]
done in 522edde51a9055c0b4e5e9b8b508b6cdde47682c
