### ISSUE TITLE
Implement a way to disable certain commands/modules

### ISSUE THREAD

**Issue by BigEBankston** [Seklfreak/Robyul2#5]
If you are looking to eventually expand gobyul's area of operation I think it'd be a great idea to implement a way to disable commands in a specific server based on the server owners own desires/needs.

**Comment by Seklfreak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Module permission system](https://trello.com/c/kNvAg0Wo/37-module-permission-system)
